### ISSUE TITLE
Just archive this repo.

### ISSUE THREAD

**Issue by raphael-costa** [flathub/nz.mega.MEGAsync#102]
This flatpak has been broken for literally years now. It serves no purpose other than confusing people.

Many programs don't have a flatpak, just let MEGASync be one of them. One day, if someone fixes the fundamental problems in this manifest, they can create their own repo and push it to flathub.

**Comment by loukamb** [comment]
Agreed. @jasongodev has done some effort on this end and created a [flatpak](https://github.com/jasongodev/nz.mega.MEGAsync) adapted to MEGAsync's new build system, but he wasn't granted authorship over the flatpak on flathub due to concerns of his package's possible future unmaintainability (mainly revolving around the use of regex to patch the package at build time instead of manually providing patches for every file the regex patches, which a flatpak maintainer has requested to be done instead and that jasongodev eventually agreed to).

For now, I'm using jasongodev's version of the flatpak and manually adjusting the flatpak config to install newer versions. I suggest you do that until his solution is eventually rolled in.

**Comment by tim77** [comment]
> This flatpak has been broken for literally years now. 

This flatpak stopped working properly only in the last ~6 months after the upstream made it impossible to update it. Please don't exaggerate.

> It serves no purpose other than confusing people.

At the moment it is. But it used to do his job perfectly and people used him every day for years, including me. Having a proper sandbox in such kind of app is very nice to have.

Some users encountered a bug with the selection of the directory, but this does not mean that the entire application was broken and unusable. 

> One day, if someone fixes the fundamental problems in this manifest

There are no fundamental problems in this manifest. The fundamental problem is in the application itself. And the upstream's desire to solve problems related to flathub build. Moreover, there were attempts to send the necessary patches into upstream, but the devs ignored them and did not accept them.

> One day, if someone fixes the fundamental problems in this manifest, they can create their own repo and push it to flathub.

"Someone" should never push their build to Flathub again. This is against the rules and main requirements of Flathub. A few years ago I pushed it because there was a flathub build request and the upstream didn't mind. But I hoped that in time they would be interested and start supporting this flathub build themselves. But it didn't happen.

**Comment by zefr0x** [comment]
> There are no fundamental problems in this manifest. The fundamental problem is in the application itself. And the upstream's desire to solve problems related to flathub build. Moreover, there were attempts to send the necessary patches into upstream, but the devs ignored them and did not accept them.

Cloud we have a list of those **fundamental** problems referred to here?
